### ISSUE TITLE
Adding in support for s390x and ppc64le

### ISSUE THREAD

**Issue by james-crowley** [rinchsan/gosimports#92]
@rinchsan Would you be open to adding support for `s390x` and `ppc64le`?

`s390x` refers to the mainframe architecture on Linux or common referred to Linux on Z. While `ppc64le` refers to the Power architecture. Both architectures are made by IBM, even though some of it is open source.

From my experience both s390x and ppc64le both have great support in GO and usually cross compile without issue.

I believe the `.goreleaser.yml` would need to be update to look something like:

```yaml


project_name: gosimports
changelog:
  skip: true
builds:
  - id: gosimports
    main: ./cmd/gosimports/
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - s390x
      - ppc64le
    ignore:
      - goos: darwin
        goarch: s390x
      - goos: darwin
        goarch: ppc64le
      - goos: windows
        goarch: s390x
      - goos: windows
        goarch: ppc64le
brews:
  - name: gosimports
    tap:
      owner: rinchsan
      name: homebrew-tap
    url_template: "https://github.com/rinchsan/gosimports/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    folder: Formula
    homepage: "https://pkg.go.dev/github.com/rinchsan/gosimports/cmd/gosimports"
    description: Command gosimports updates your Go import lines, adding missing ones, removing unreferenced ones, and removing redundant blank lines.
    test: |
      system "#{bin}/gosimports --help"
    install: |
      bin.install "gosimports"
```

Happy to test and validate `s390x` and `ppc64le` support as I have access to the hardware. If there are not issues, I would be happy to open a PR. 

@rinchsan Let me know if you are open to the idea!
